### PR TITLE
Create German language (& suggestions)

### PR DESCRIPTION
**Pull request by Slluxx**
Please note that i had to add an argument to `WhenFreeMemoryIsBelow`, otherwise the grammar would be incorrect. I was able to avoid this issue with other sentences but it doesn't sound as good as it could. **Reflect that in the source code before merging.**

If you have a sentence, you should always create arguments (for variables) to avoid this kind of issue in other languages in the future.

`ErrorFeatureIsNotSupported` is kind of unclear, as there is no example of how this is used. Especially the word "clean" in the english translation is confusing because without knowing what the entire sentence could be, it does not make sense.

I also noticed that there is no way to preview a language without building the entire thing first. You should check if there are JSON files with a certain pattern in the current working directory (for example `.*.wmc.json`) so other people can quickly make & test languages without the need to compile it.

On another note, the checkboxes for "Standby List" have a different spacing to each other than the rest. It _may_ have been done for grouping them but IMHO they should have the same spacing.

### CODE REVIEW

**Comment by IgorMundstein** [comment]
Thanks for the contribution. No need for PR. You could upload the file from the [translation discussion](https://github.com/IgorMundstein/WinMemoryCleaner/discussions/14).

> Please note that i had to add an argument to WhenFreeMemoryIsBelow, otherwise the grammar would be incorrect. I was able to avoid this issue with other sentences but it doesn't sound as good as it could. Reflect that in the source code before merging. If you have a sentence, you should always create arguments (for variables) to avoid this kind of issue in other languages in the future.

I got it. I must check how to handle it on XAML because it's a dynamic property. I hope multi bind works.

> `ErrorFeatureIsNotSupported is kind of unclear, as there is no example of how this is used. Especially the word "clean" in the english translation is confusing because without knowing what the entire sentence could be, it does not make sense.`

Some memory areas are not available on older Windows versions. The parameter is basically the memory area name. So, it will something like: "Combined Page List clean is not supported on this operating system version". I already add other checks and this message unlikely will be called.

> I also noticed that there is no way to preview a language without building the entire thing first. You should check if there are JSON files with a certain pattern in the current working directory (for example .*.wmc.json) so other people can quickly make & test languages without the need to compile it.

The app works with Culture, not just Language. That means the number and date formats change. For example, the US uses MM/DD/YYYY but other cultures use DD/MM/YYYY. As well, $1,234.56 vs 1.234,56
So, I have to set an enumerator with the respective LCID to change the culture. I also show the native language name, not just the English language name.

So, it's just not reading an external file. However, the idea is not bad. I just need to think of a better way to implement it.

**Comment by Slluxx** [comment]
> Thanks for the contribution. No need for PR. You could upload the file from the https://github.com/IgorMundstein/WinMemoryCleaner/discussions/14.

Ah sorry, i completely overlooked that in the readme. Just saw the en.json link and went ahead and did it this way.

> Some memory areas are not available on older Windows versions. The parameter is basically the memory area name. So, it will something like: "Combined Page List clean is not supported on this operating system version". I already add other checks and this message unlikely will be called.

Aah, now it makes sense. It should be fine then. German translations always sound odd, that the nature of this language i guess.

> The app works with Culture, not just Language. That means the number and date formats change. For example, the US uses MM/DD/YYYY but other cultures use DD/MM/YYYY. As well, $1,234.56 vs 1.234,56
So, I have to set an enumerator with the respective LCID to change the culture. I also show the native language name, not just the English language name.

I see. That makes things more complicated but im sure you will figure something out!

BTW, great app. I am rocking 8 gigs in this pc, running a custom version of windows 10 to minimize ram usage and combined with your tool, i can get down to 1.1 usage in idle (in a custom win7 install with 4 gigs i was able to get down to 650mb idle, its insane).

**Comment by IgorMundstein** [comment]
> Ah sorry, i completely overlooked that in the readme. Just saw the en.json link and went ahead and did it this way.

No worries. 

> Aah, now it makes sense. It should be fine then. German translations always sound odd, that the nature of this language i guess.

It's funny because English is derived from German and English doesn't have a grammatical gender as many other languages do. I know how complex it is. I have a German bloodline because my great-grandparents were holocaust refugees, but unfortunately, I didn't learn the language.

> BTW, great app. I am rocking 8 gigs in this pc, running a custom version of windows 10 to minimize ram usage and combined with your tool, i can get down to 1.1 usage in idle (in a custom win7 install with 4 gigs i was able to get down to 650mb idle, its insane).

I know. Windows doesn't handle memory management very well because this application only calls Windows' memory cleanup functions.

**Comment by IgorMundstein** [comment]
Translation added.

Please, review the 2.1 version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.1

**Pull request closed without merging**
