### PR TITLE
优化中文

### PR DESCRIPTION
**Pull request by Fgaoxing**
这里我认为翻译成“物理内存”更合适

### CODE REVIEW

**Comment by Fgaoxing** [comment]
@IgorMundstein

**Comment by IgorMundstein** [comment]
Thanks for the suggestion, but I only need the word Physical because it saves space and is not redundant. Otherwise, Physical Memory and Virtual Memory will be in the same place. The word Memory is used twice. Since it's a memory app, physical and virtual are implicit in the context.

image

image

**Comment by Fgaoxing** [comment]
@IgorMundstein 可以改为“物理”

**Comment by Fgaoxing** [comment]
而不是现有的“身体”

**Pull request closed without merging**
